import os
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()


def generate_text(prompt: str) -> str:
    """Return text generated by Google Gemini model."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is not set")
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content(prompt)
    return getattr(response, "text", str(response))
